import type { SelectOption } from '@/components/ui/Select';

/**
 * One representative IANA timezone per `lib/countries.ts` entry — the
 * capital/most-populous zone for countries that span more than one (e.g.
 * `US` → `America/New_York`, not every US zone; `RU` → `Europe/Moscow`).
 * Drives the *default* selection in `BranchSetupForm`'s Timezone dropdown
 * (see `timezoneOptionsFor` below for the actual list of choices) — a
 * hotel outside the default zone still picks the right one from that same
 * dropdown, it's not stuck with this guess.
 */
export const DEFAULT_TIMEZONE_BY_COUNTRY: Record<string, string> = {
  AF: 'Asia/Kabul',
  AL: 'Europe/Tirane',
  DZ: 'Africa/Algiers',
  AD: 'Europe/Andorra',
  AO: 'Africa/Luanda',
  AG: 'America/Antigua',
  AR: 'America/Argentina/Buenos_Aires',
  AM: 'Asia/Yerevan',
  AU: 'Australia/Sydney',
  AT: 'Europe/Vienna',
  AZ: 'Asia/Baku',
  BS: 'America/Nassau',
  BH: 'Asia/Bahrain',
  BD: 'Asia/Dhaka',
  BB: 'America/Barbados',
  BY: 'Europe/Minsk',
  BE: 'Europe/Brussels',
  BZ: 'America/Belize',
  BJ: 'Africa/Porto-Novo',
  BT: 'Asia/Thimphu',
  BO: 'America/La_Paz',
  BA: 'Europe/Sarajevo',
  BW: 'Africa/Gaborone',
  BR: 'America/Sao_Paulo',
  BN: 'Asia/Brunei',
  BG: 'Europe/Sofia',
  BF: 'Africa/Ouagadougou',
  BI: 'Africa/Bujumbura',
  CV: 'Atlantic/Cape_Verde',
  KH: 'Asia/Phnom_Penh',
  CM: 'Africa/Douala',
  CA: 'America/Toronto',
  CF: 'Africa/Bangui',
  TD: 'Africa/Ndjamena',
  CL: 'America/Santiago',
  CN: 'Asia/Shanghai',
  CO: 'America/Bogota',
  KM: 'Indian/Comoro',
  CG: 'Africa/Brazzaville',
  CD: 'Africa/Kinshasa',
  CR: 'America/Costa_Rica',
  CI: 'Africa/Abidjan',
  HR: 'Europe/Zagreb',
  CU: 'America/Havana',
  CY: 'Asia/Nicosia',
  CZ: 'Europe/Prague',
  DK: 'Europe/Copenhagen',
  DJ: 'Africa/Djibouti',
  DM: 'America/Dominica',
  DO: 'America/Santo_Domingo',
  EC: 'America/Guayaquil',
  EG: 'Africa/Cairo',
  SV: 'America/El_Salvador',
  GQ: 'Africa/Malabo',
  ER: 'Africa/Asmara',
  EE: 'Europe/Tallinn',
  SZ: 'Africa/Mbabane',
  ET: 'Africa/Addis_Ababa',
  FJ: 'Pacific/Fiji',
  FI: 'Europe/Helsinki',
  FR: 'Europe/Paris',
  GA: 'Africa/Libreville',
  GM: 'Africa/Banjul',
  GE: 'Asia/Tbilisi',
  DE: 'Europe/Berlin',
  GH: 'Africa/Accra',
  GR: 'Europe/Athens',
  GD: 'America/Grenada',
  GT: 'America/Guatemala',
  GN: 'Africa/Conakry',
  GW: 'Africa/Bissau',
  GY: 'America/Guyana',
  HT: 'America/Port-au-Prince',
  HN: 'America/Tegucigalpa',
  HU: 'Europe/Budapest',
  IS: 'Atlantic/Reykjavik',
  IN: 'Asia/Kolkata',
  ID: 'Asia/Jakarta',
  IR: 'Asia/Tehran',
  IQ: 'Asia/Baghdad',
  IE: 'Europe/Dublin',
  IL: 'Asia/Jerusalem',
  IT: 'Europe/Rome',
  JM: 'America/Jamaica',
  JP: 'Asia/Tokyo',
  JO: 'Asia/Amman',
  KZ: 'Asia/Almaty',
  KE: 'Africa/Nairobi',
  KI: 'Pacific/Tarawa',
  KW: 'Asia/Kuwait',
  KG: 'Asia/Bishkek',
  LA: 'Asia/Vientiane',
  LV: 'Europe/Riga',
  LB: 'Asia/Beirut',
  LS: 'Africa/Maseru',
  LR: 'Africa/Monrovia',
  LY: 'Africa/Tripoli',
  LI: 'Europe/Vaduz',
  LT: 'Europe/Vilnius',
  LU: 'Europe/Luxembourg',
  MG: 'Indian/Antananarivo',
  MW: 'Africa/Blantyre',
  MY: 'Asia/Kuala_Lumpur',
  MV: 'Indian/Maldives',
  ML: 'Africa/Bamako',
  MT: 'Europe/Malta',
  MR: 'Africa/Nouakchott',
  MU: 'Indian/Mauritius',
  MX: 'America/Mexico_City',
  MD: 'Europe/Chisinau',
  MC: 'Europe/Monaco',
  MN: 'Asia/Ulaanbaatar',
  ME: 'Europe/Podgorica',
  MA: 'Africa/Casablanca',
  MZ: 'Africa/Maputo',
  MM: 'Asia/Yangon',
  NA: 'Africa/Windhoek',
  NR: 'Pacific/Nauru',
  NP: 'Asia/Kathmandu',
  NL: 'Europe/Amsterdam',
  NZ: 'Pacific/Auckland',
  NI: 'America/Managua',
  NE: 'Africa/Niamey',
  NG: 'Africa/Lagos',
  KP: 'Asia/Pyongyang',
  MK: 'Europe/Skopje',
  NO: 'Europe/Oslo',
  OM: 'Asia/Muscat',
  PK: 'Asia/Karachi',
  PW: 'Pacific/Palau',
  PA: 'America/Panama',
  PG: 'Pacific/Port_Moresby',
  PY: 'America/Asuncion',
  PE: 'America/Lima',
  PH: 'Asia/Manila',
  PL: 'Europe/Warsaw',
  PT: 'Europe/Lisbon',
  QA: 'Asia/Qatar',
  RO: 'Europe/Bucharest',
  RU: 'Europe/Moscow',
  RW: 'Africa/Kigali',
  KN: 'America/St_Kitts',
  LC: 'America/St_Lucia',
  VC: 'America/St_Vincent',
  WS: 'Pacific/Apia',
  SM: 'Europe/San_Marino',
  ST: 'Africa/Sao_Tome',
  SA: 'Asia/Riyadh',
  SN: 'Africa/Dakar',
  RS: 'Europe/Belgrade',
  SC: 'Indian/Mahe',
  SL: 'Africa/Freetown',
  SG: 'Asia/Singapore',
  SK: 'Europe/Bratislava',
  SI: 'Europe/Ljubljana',
  SB: 'Pacific/Guadalcanal',
  SO: 'Africa/Mogadishu',
  ZA: 'Africa/Johannesburg',
  KR: 'Asia/Seoul',
  SS: 'Africa/Juba',
  ES: 'Europe/Madrid',
  LK: 'Asia/Colombo',
  SD: 'Africa/Khartoum',
  SR: 'America/Paramaribo',
  SE: 'Europe/Stockholm',
  CH: 'Europe/Zurich',
  SY: 'Asia/Damascus',
  TW: 'Asia/Taipei',
  TJ: 'Asia/Dushanbe',
  TZ: 'Africa/Dar_es_Salaam',
  TH: 'Asia/Bangkok',
  TL: 'Asia/Dili',
  TG: 'Africa/Lome',
  TO: 'Pacific/Tongatapu',
  TT: 'America/Port_of_Spain',
  TN: 'Africa/Tunis',
  TR: 'Europe/Istanbul',
  TM: 'Asia/Ashgabat',
  TV: 'Pacific/Funafuti',
  UG: 'Africa/Kampala',
  UA: 'Europe/Kyiv',
  AE: 'Asia/Dubai',
  GB: 'Europe/London',
  US: 'America/New_York',
  UY: 'America/Montevideo',
  UZ: 'Asia/Tashkent',
  VU: 'Pacific/Efate',
  VA: 'Europe/Vatican',
  VE: 'America/Caracas',
  VN: 'Asia/Ho_Chi_Minh',
  YE: 'Asia/Aden',
  ZM: 'Africa/Lusaka',
  ZW: 'Africa/Harare',
};

export function defaultTimezoneFor(country: string | null | undefined): string | null {
  if (!country) return null;
  return DEFAULT_TIMEZONE_BY_COUNTRY[country] ?? null;
}

/**
 * Every real IANA zone for countries that genuinely span more than one —
 * the actual fix for "a single country can have multiple timezones"
 * (Denver vs. New York, Perth vs. Sydney, ...), not just a better guess.
 * Deliberately not exhaustive down to every minor historical/exception
 * sub-zone IANA tracks (e.g. US's `America/Indiana/*` county exceptions,
 * Russia's very smallest regions) — the primary zones covering where
 * hotels actually operate. Every country *not* listed here has exactly one
 * real zone, so `timezoneOptionsFor` falls back to
 * `DEFAULT_TIMEZONE_BY_COUNTRY` for the other 175+ entries rather than
 * hand-listing a thousand-plus single-item arrays.
 */
const MULTI_ZONE_COUNTRIES: Record<string, SelectOption[]> = {
  US: [
    { value: 'America/New_York', label: 'Eastern — America/New_York' },
    { value: 'America/Chicago', label: 'Central — America/Chicago' },
    { value: 'America/Denver', label: 'Mountain — America/Denver' },
    { value: 'America/Phoenix', label: 'Mountain, no DST — America/Phoenix' },
    { value: 'America/Los_Angeles', label: 'Pacific — America/Los_Angeles' },
    { value: 'America/Anchorage', label: 'Alaska — America/Anchorage' },
    { value: 'Pacific/Honolulu', label: 'Hawaii — Pacific/Honolulu' },
  ],
  CA: [
    { value: 'America/St_Johns', label: 'Newfoundland — America/St_Johns' },
    { value: 'America/Halifax', label: 'Atlantic — America/Halifax' },
    { value: 'America/Toronto', label: 'Eastern — America/Toronto' },
    { value: 'America/Winnipeg', label: 'Central — America/Winnipeg' },
    { value: 'America/Edmonton', label: 'Mountain — America/Edmonton' },
    { value: 'America/Vancouver', label: 'Pacific — America/Vancouver' },
  ],
  RU: [
    { value: 'Europe/Kaliningrad', label: 'Kaliningrad — Europe/Kaliningrad' },
    { value: 'Europe/Moscow', label: 'Moscow — Europe/Moscow' },
    { value: 'Europe/Samara', label: 'Samara — Europe/Samara' },
    { value: 'Asia/Yekaterinburg', label: 'Yekaterinburg — Asia/Yekaterinburg' },
    { value: 'Asia/Omsk', label: 'Omsk — Asia/Omsk' },
    { value: 'Asia/Novosibirsk', label: 'Novosibirsk — Asia/Novosibirsk' },
    { value: 'Asia/Krasnoyarsk', label: 'Krasnoyarsk — Asia/Krasnoyarsk' },
    { value: 'Asia/Irkutsk', label: 'Irkutsk — Asia/Irkutsk' },
    { value: 'Asia/Yakutsk', label: 'Yakutsk — Asia/Yakutsk' },
    { value: 'Asia/Vladivostok', label: 'Vladivostok — Asia/Vladivostok' },
    { value: 'Asia/Magadan', label: 'Magadan — Asia/Magadan' },
    { value: 'Asia/Kamchatka', label: 'Kamchatka — Asia/Kamchatka' },
  ],
  AU: [
    { value: 'Australia/Perth', label: 'Western — Australia/Perth' },
    { value: 'Australia/Darwin', label: 'Central, no DST — Australia/Darwin' },
    { value: 'Australia/Adelaide', label: 'Central — Australia/Adelaide' },
    { value: 'Australia/Brisbane', label: 'Eastern, no DST — Australia/Brisbane' },
    { value: 'Australia/Sydney', label: 'Eastern — Australia/Sydney' },
    { value: 'Australia/Lord_Howe', label: 'Lord Howe Island — Australia/Lord_Howe' },
  ],
  BR: [
    { value: 'America/Noronha', label: 'Fernando de Noronha — America/Noronha' },
    { value: 'America/Sao_Paulo', label: 'Brasília — America/Sao_Paulo' },
    { value: 'America/Manaus', label: 'Amazon — America/Manaus' },
    { value: 'America/Rio_Branco', label: 'Acre — America/Rio_Branco' },
  ],
  MX: [
    { value: 'America/Cancun', label: 'Southeast — America/Cancun' },
    { value: 'America/Mexico_City', label: 'Central — America/Mexico_City' },
    { value: 'America/Chihuahua', label: 'Pacific — America/Chihuahua' },
    { value: 'America/Hermosillo', label: 'Sonora, no DST — America/Hermosillo' },
    { value: 'America/Tijuana', label: 'Northwest — America/Tijuana' },
  ],
  ID: [
    { value: 'Asia/Jakarta', label: 'Western — Asia/Jakarta' },
    { value: 'Asia/Makassar', label: 'Central — Asia/Makassar' },
    { value: 'Asia/Jayapura', label: 'Eastern — Asia/Jayapura' },
  ],
  CD: [
    { value: 'Africa/Kinshasa', label: 'West — Africa/Kinshasa' },
    { value: 'Africa/Lubumbashi', label: 'East — Africa/Lubumbashi' },
  ],
  KZ: [
    { value: 'Asia/Almaty', label: 'East — Asia/Almaty' },
    { value: 'Asia/Aqtobe', label: 'West — Asia/Aqtobe' },
  ],
  MN: [
    { value: 'Asia/Ulaanbaatar', label: 'East — Asia/Ulaanbaatar' },
    { value: 'Asia/Hovd', label: 'West — Asia/Hovd' },
  ],
  CL: [
    { value: 'America/Santiago', label: 'Mainland — America/Santiago' },
    { value: 'Pacific/Easter', label: 'Easter Island — Pacific/Easter' },
  ],
  EC: [
    { value: 'America/Guayaquil', label: 'Mainland — America/Guayaquil' },
    { value: 'Pacific/Galapagos', label: 'Galápagos — Pacific/Galapagos' },
  ],
  PT: [
    { value: 'Europe/Lisbon', label: 'Mainland — Europe/Lisbon' },
    { value: 'Atlantic/Madeira', label: 'Madeira — Atlantic/Madeira' },
    { value: 'Atlantic/Azores', label: 'Azores — Atlantic/Azores' },
  ],
  ES: [
    { value: 'Europe/Madrid', label: 'Mainland — Europe/Madrid' },
    { value: 'Atlantic/Canary', label: 'Canary Islands — Atlantic/Canary' },
  ],
  NZ: [
    { value: 'Pacific/Auckland', label: 'Mainland — Pacific/Auckland' },
    { value: 'Pacific/Chatham', label: 'Chatham Islands — Pacific/Chatham' },
  ],
  KI: [
    { value: 'Pacific/Tarawa', label: 'Gilbert Islands — Pacific/Tarawa' },
    { value: 'Pacific/Enderbury', label: 'Phoenix Islands — Pacific/Enderbury' },
    { value: 'Pacific/Kiritimati', label: 'Line Islands — Pacific/Kiritimati' },
  ],
};

/**
 * The actual dropdown options for `BranchSetupForm`'s Timezone field —
 * every real zone for the ~15 countries that genuinely have more than one,
 * a single option (from `DEFAULT_TIMEZONE_BY_COUNTRY`) for everyone else.
 * `[]` before a country is picked (nothing to choose from yet, matches
 * Country being a required field upstream of this one).
 */
export function timezoneOptionsFor(country: string | null | undefined): SelectOption[] {
  if (!country) return [];
  const multi = MULTI_ZONE_COUNTRIES[country];
  if (multi) return multi;
  const single = DEFAULT_TIMEZONE_BY_COUNTRY[country];
  return single ? [{ value: single, label: single }] : [];
}
